name: flutter_shopping_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  intl: ^0.16.0
  url_launcher: 5.4.2
  get_it: 4.0.1
  auto_route: 0.6.7
  connectivity: 0.4.8+2
  cached_network_image: ^2.2.0
  json_annotation: 3.0.1
  shimmer: 1.1.1
  package_info: ^0.4.0+18
  fluttertoast: ^4.0.0
  smooth_page_indicator: 0.1.5
  freezed: 0.10.9
  flutter_bloc: 6.0.5
  provider: 4.3.1
  shared_preferences:
  dio:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.10.0
  json_serializable: ^3.2.3
  auto_route_generator: 0.6.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
